<a href="https://colab.research.google.com/github/Paritala-Sai-Krishna-Anoop/Essential-math-for-ML/blob/main/vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [ ]:
print(v+w)

[3 4 4]


In [ ]:
print(v-w)

[-1 -6  0]


In [ ]:
#Scalar muliplication:
print(3*v)

[ 3 -3  6]


In [ ]:
#length/magnitude of the vector:
print(np.linalg.norm(v))

2.449489742783178


In [ ]:
#dot product
s=(np.dot(v,w))
print(s)

1
